# Generated by Django 3.0.1 on 2019-12-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='general',
            field=models.BooleanField(default=False, verbose_name='general'),
        ),
        migrations.AddField(
            model_name='school',
            name='smart',
            field=models.BooleanField(default=False, verbose_name='smart'),
        ),
    ]
