# Generated by Django 3.0.1 on 2019-12-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191225_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Available_stream_after_10th',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='CCTV',
            field=models.BooleanField(default=False, verbose_name='Present'),
        ),
        migrations.AddField(
            model_name='school',
            name='Commuting_Facilities',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='From_Class',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th')], default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='Mention',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='Safety_Security_and_Meausures',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='Students_per_Teachers',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='Total_Students',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='Type_of_Board',
            field=models.CharField(choices=[('1st', 'state'), ('2nd', 'CBSE'), ('3rd', 'ICSE'), ('4th', 'Others')], default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='to',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('12th', '12th')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_addesss',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
