# Generated by Django 3.0.1 on 2019-12-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191225_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
