# Generated by Django 3.0.1 on 2019-12-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191225_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Available_stream_after_10th',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='CCTV',
            field=models.BooleanField(blank=True, verbose_name='Present'),
        ),
        migrations.AlterField(
            model_name='school',
            name='CCTV1',
            field=models.BooleanField(blank=True, verbose_name='Not Present'),
        ),
        migrations.AlterField(
            model_name='school',
            name='Commuting_Facilities',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='Damege_to_Property',
            field=models.BooleanField(blank=True, verbose_name='Damege_to_Property'),
        ),
        migrations.AlterField(
            model_name='school',
            name='From_Class',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th')], max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='Mention',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='Misbehaving',
            field=models.BooleanField(blank=True, verbose_name='Misbehaving'),
        ),
        migrations.AlterField(
            model_name='school',
            name='Safety_Security_and_Meausures',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='Students_per_Teachers',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='Total_Students',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='Type_of_Board',
            field=models.CharField(blank=True, choices=[('1st', 'state'), ('2nd', 'CBSE'), ('3rd', 'ICSE'), ('4th', 'Others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='general',
            field=models.BooleanField(blank=True, verbose_name='general'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_addesss',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='smart',
            field=models.BooleanField(blank=True, verbose_name='smart'),
        ),
        migrations.AlterField(
            model_name='school',
            name='to',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('12th', '12th')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='school',
            table='School',
        ),
    ]
