# Generated by Django 3.0.1 on 2019-12-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191225_1613'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='school',
            table=None,
        ),
    ]
