# Generated by Django 3.0.1 on 2019-12-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='Timings',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
