# Generated by Django 3.0.1 on 2019-12-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191226_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='Frequenct_of_Class',
            new_name='Frequency_of_Class',
        ),
    ]
