# Generated by Django 3.0.1 on 2019-12-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191226_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('addesss', models.CharField(blank=True, max_length=50)),
                ('Phone_number', models.IntegerField(blank=True, max_length=10)),
                ('Email_id', models.EmailField(blank=True, max_length=254)),
                ('Timings', models.CharField(blank=True, max_length=10)),
                ('Subjects', models.CharField(blank=True, max_length=50)),
                ('Class_being_Tought', models.CharField(blank=True, max_length=50)),
                ('Years_of_Experience', models.CharField(blank=True, max_length=50)),
                ('Educationnal_Qualification', models.CharField(blank=True, max_length=50)),
                ('Fees', models.IntegerField(blank=True, max_length=50)),
                ('Frequency_of_Class', models.CharField(blank=True, max_length=50)),
                ('About', models.TextField(blank=True, max_length=50)),
            ],
        ),
    ]
