# Generated by Django 3.0.1 on 2019-12-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_school_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='password',
        ),
    ]
